---
apiVersion: batch/v1
kind: Job
metadata:
  name: ghodrat-ion-sfu
  labels:
    app.kubernetes.io/name: ghodrat-ion-sfu
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghodrat-ion-sfu
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ghodrat-ion-sfu
          image: ghcr.io/snapp-incubator/ghodrat-ion-sfu:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ghodrat-ion-sfu
