name: Build

on:
  workflow_run:
    workflows: ["Compile"]
    branches: [master, develop]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build
    strategy:
      matrix:
        service: [janus]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-binary
      - run: ls .
