name: Setup

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install & cache dependencies
        run: go mod vendor
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: install & upload build binary
        run: go build -mod=vendor -o ./output ./cmd/root.go
        uses: actions/upload-artifact@v2
        with:
          name: build-binary
          path: output
