---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "ghodrat-janus"
  labels:
    app.kubernetes.io/name: "ghodrat-janus"
data:
  ghodrat_call-count: "100"

  ghodrat_logger_development: "false"
  ghodrat_logger_encoding: "json"
  ghodrat_logger_level: "info"

  ghodrat_tracer_enabled: "false"
  ghodrat_tracer_host: ""
  ghodrat_tracer_port: "6831"
  ghodrat_tracer_sample-rate: "0.1"

  ghodrat_client_track-address: "bin/ghodrat/audio.ogg"
  ghodrat_client_stun-server: "stun:stun.l.google.com:19302"
  ghodrat_client_rtp-codec_rtp-codec_mime-type: "audio/opus"
  ghodrat_client_rtp-codec_rtp-codec_clock-rate: "48000"
  ghodrat_client_rtp-codec_rtp-codec_channels: "2"
  ghodrat_client_rtp-codec_rtp-codec_payload-type: "111"
  ghodrat_client_rtp-codec_rtp-codec_codec-type: "1"

  ghodrat_janus_address: "ws://janus:8188"
