---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghodrat-janus
  labels:
    app.kubernetes.io/name: ghodrat-janus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ghodrat-janus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghodrat-janus
    spec:
      containers:
        - name: ghodrat-janus
          image: ghcr.io/snapp-incubator/ghodrat-janus:master
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: ghodrat-janus
