---
apiVersion: batch/v1
kind: Job
metadata:
  name: ghodrat-janus
  labels:
    app.kubernetes.io/name: ghodrat-janus
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghodrat-janus
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ghodrat-janus
          image: ghcr.io/snapp-incubator/ghodrat-janus:v1.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: ghodrat-janus
